name: 'npm'
description: 'An action to create an npm package and push it to artifactory'

inputs:
  npm_repo:
    required: true
  npm_email:
    required: true
  npm_secret:
    description: 'artifatory npm secret'
    required: true
runs:
  using: "composite"
  steps:
    - name: Log in to the npm registry
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name : publish to registery jfrog
      env:
          ARTIFACTORY_EMAIL: ${{ inputs.npm_email }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      run: 
        |
          echo "email = $ARTIFACTORY_EMAIL
            always-auth = true
            registry=https://$ARTIFACTORY_URL
            //$ARTIFACTORY_URL:_authToken=$ARTIFACTORY_PASSWORD" > ~/.npmrc |
    - name : publish to artifactory
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      run: npm publish --registry https://$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/
