name: 'npm'
description: 'An action to create an npm package and push it to artifactory'

inputs:
  npm_repo:
    required: true
  secret:
    description: 'artifatory npm secret'
    required: true
runs:
  using: "composite"
  steps:
    - name: Log in to the npm registry
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'
    - run: npm set registery="${{ inputs.npm_repo}}//${{ inputs.npm_repo}}/:_authToken=${{ inputs.secret }}"
    - run: npm publish
