name: npm
description: An action to create an npm package and push it to artifactory

inputs:
  npm_repo:
    required: true
  npm_email:
    required: true
  npm_secret:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Log in to the npm registry
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      shell: bash
      run: npm install
      
    - name : publish to registery jfrog
      shell: bash
      env:
          ARTIFACTORY_EMAIL: ${{ inputs.npm_email }}
          ARTIFACTORY_PASSWORD: ${{ inputs.npm_secret }}
          ARTIFACTORY_URL: ${{ inputs.npm_repo }}
      run: 
        |
          echo "email = $ARTIFACTORY_EMAIL
            always-auth = true
            registry=https://$ARTIFACTORY_URL
            //$ARTIFACTORY_URL:_authToken=$ARTIFACTORY_PASSWORD" > ~/.npmrc |
            
    - name : publish to artifactory
      shell: bash
      env:
        ARTIFACTORY_URL: ${{ inputs.npm_repo }}
      run: npm publish --registry https://$ARTIFACTORY_URL
