name: test-and-publish
on:
  push:
  pull_request_target:
    types: [opened, synchronize, edited]
  status: {}
jobs:
  build-test-merge-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
      - uses: bbeesley/build-test-merge-publish@main
        with:
          install-command: npm i
          build-command: npm run build
          release-command: npm run release
          main-branch: master
          merge-method: REBASE
          private-npm-registry: https://trialk033s3.jfrog.io/artifactory/api/npm/paris-npm/
          private-npm-token: ${{ secrets.JFROG_NPM_TOKEN }}
          auto-merge-bot: my-automation-bot
