name: Check sources
on:
  push:
    branches:
      main
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - uses: ./.github/actions/npm
        with:
          npm_repo: ${{ secrets.JFROG_NPM_URL }}
          npm_email: ${{ secrets.JFROG_NPM_EMAIL }}
          npm_secret: ${{ secrets.JFROG_NPM_TOKEN }}
