name: Check sources
on:
  push:
    branches:
      main
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - uses: ./.github/actions/npm
        with:
          npm_repo: trialk033s3.jfrog.io/artifactory/api/npm/paris-npm/
          npm_email: lylia.ait.zerrouk@gmail.com
          npm_secret: ${{ secrets.JFROG_NPM_TOKEN }}
