name: Check sources
on:
  push:
    branches: 
      - main
jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - uses: ./.github/actions/npm
        with:
          npm_repo: https://trialk033s3.jfrog.io/artifactory/api/npm/paris-npm/
          actor: lylia
          secret: ${{ secrets.JFROG_NPM_TOKEN }}
